Test Build.yml of `luci-app-xray`

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,64 +1,124 @@
 name: Build
 
 on:
-  workflow_dispatch:
-  pull_request:
-    branches:
-      - master
   push:
-  release:
+    tags:
+      - "*"
+  workflow_dispatch:
+
+env:
+  PACKAGE_NAME: luci-app-scutclient
+  CACHE_DIR: ~/cache
 
 jobs:
-  build:
-    name: ${{ matrix.arch }} build
+  release:
+    name: Build for ${{ matrix.arch }}
     runs-on: ubuntu-latest
     strategy:
+      fail-fast: false
       matrix:
-        arch:
-          # - aarch64_cortex-a53
-          # - aarch64_cortex-a72
-          # - aarch64_generic
-          # - arm_arm1176jzf-s_vfp
-          # - arm_cortex-a15_neon-vfpv4
-          # - arm_cortex-a5_vfpv4
-          # - arm_cortex-a7
-          # - arm_cortex-a7_neon-vfpv4
-          # - arm_cortex-a7_vfpv4
-          # - arm_cortex-a8_vfpv3
-          # - arm_cortex-a9
-          # - arm_cortex-a9_neon
-          # - arm_cortex-a9_vfpv3-d16
-          # - i386_pentium4
-          # - i386_pentium-mmx
-          # - mips_24kc
-          # - mips_4kec
-          # - mipsel_24kc
-          # - mipsel_24kc_24kf
-          # - mipsel_74kc
-          # - mipsel_mips32
-          # - mips_mips32
-          - x86_64
+        include:
+          - arch: x86_64
+            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/x86/64
+            sdk_name: -sdk-x86-64_
 
+    env:
+      SDK_URL_PATH: ${{ matrix.sdk_url_path }}
+      SDK_NAME: ${{ matrix.sdk_name }}
+      CCACHE_DIR: ~/.ccache
+      CONFIG_CCACHE: y
     steps:
-      - uses: actions/checkout@main
-        with:
-          fetch-depth: 0
+      - name: Checkout
+        uses: actions/checkout@v3
 
-      - name: Prepare package
+      - name: Prepare Cache Key
+        id: cache_key
+        run: echo "::set-output name=timestamp::$(date +"%s")"
+
+      - name: Setup Cache
+        uses: actions/cache@v2
+        with:
+          path: |
+            ${{ env.CACHE_DIR }}
+            ${{ env.CCACHE_DIR }}
+          key: openwrt-${{ matrix.arch }}-${{ env.PACKAGE_NAME }}-${{ steps.cache_key.outputs.timestamp }}
+          restore-keys: |
+            openwrt-${{ matrix.arch }}-${{ env.PACKAGE_NAME }}-
+      - name: Install Dependencies
         run: |
-          sed -i '/^SRCDIR/ s/$/\/feed/' Makefile
-          mkdir -p feed/luci/applications/luci-app-scutclient
-          mv Makefile feed/luci/applications/luci-app-scutclient/
-          cat feed/luci/applications/luci-app-scutclient/Makefile
-      - name: Build
-        uses: openwrt/gh-action-sdk@main
-        env:
-          ARCH: ${{ matrix.arch }}
-          NO_DEFAULT_FEEDS: 1
-          PACKAGES: luci-app-scutclient
+          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y ccache gettext libncurses5-dev xsltproc
+      - name: Create Directories
+        run: |
+          CACHE_DIR_SDK="$(eval echo "$CACHE_DIR/sdk")"
+          CACHE_DIR_DL="$(eval echo "$CACHE_DIR/dl")"
+          CACHE_DIR_FEEDS="$(eval echo "$CACHE_DIR/feeds")"
+          echo "CACHE_DIR_SDK: $CACHE_DIR_SDK"
+          echo "CACHE_DIR_DL: $CACHE_DIR_DL"
+          echo "CACHE_DIR_FEEDS: $CACHE_DIR_FEEDS"
+          test -d "$CACHE_DIR_SDK" || mkdir -p "$CACHE_DIR_SDK"
+          test -d "$CACHE_DIR_DL" || mkdir -p "$CACHE_DIR_DL"
+          test -d "$CACHE_DIR_FEEDS" || mkdir -p "$CACHE_DIR_FEEDS"
+          echo "CACHE_DIR_SDK=$CACHE_DIR_SDK" >> $GITHUB_ENV
+          echo "CACHE_DIR_DL=$CACHE_DIR_DL" >> $GITHUB_ENV
+          echo "CACHE_DIR_FEEDS=$CACHE_DIR_FEEDS" >> $GITHUB_ENV
+          echo "SDK_HOME=$(mktemp -d)" >> $GITHUB_ENV
+      - name: Download and Unzip SDK
+        run: |
+          cd "$CACHE_DIR_SDK"
+          if ! ( wget -q -O - "$SDK_URL_PATH/sha256sums" | grep -- "$SDK_NAME" > sha256sums.small 2>/dev/null ) ; then
+            echo "::error::Can not find ${SDK_NAME} file in sha256sums."
+            exit 1
+          fi
+          SDK_FILE="$(cat sha256sums.small | cut -d' ' -f2 | sed 's/*//g')"
+          if ! sha256sum -c ./sha256sums.small >/dev/null 2>&1 ; then
+            wget -q -O "$SDK_FILE" "$SDK_URL_PATH/$SDK_FILE"
+            if ! sha256sum -c ./sha256sums.small >/dev/null 2>&1 ; then
+              echo "::error::SDK can not be verified!"
+              exit 1
+            fi
+          fi
+          cd -
+          file "$CACHE_DIR_SDK/$SDK_FILE"
+          tar -I zstd -xvf "$CACHE_DIR_SDK/$SDK_FILE" -C "$SDK_HOME" --strip=1
+          cd "$SDK_HOME"
+          test -d "dl" && rm -rf "dl" || true
+          test -d "feeds" && rm -rf "feeds" || true
+          ln -s "$CACHE_DIR_DL" "dl"
+          ln -s "$CACHE_DIR_FEEDS" "feeds"
+          cp feeds.conf.default feeds.conf
+          sed -i 's#git.openwrt.org/openwrt/openwrt#github.com/openwrt/openwrt#' feeds.conf
+          sed -i 's#git.openwrt.org/feed/packages#github.com/openwrt/packages#' feeds.conf
+          sed -i 's#git.openwrt.org/project/luci#github.com/openwrt/luci#' feeds.conf
+          sed -i 's#git.openwrt.org/feed/telephony#github.com/openwrt/telephony#' feeds.conf
+          cd -
+      - name: Update and Install Packages
+        run: |
+          cd "$SDK_HOME"
+          ./scripts/feeds update -a
+          ln -s "${{ github.workspace }}" "package/$PACKAGE_NAME"
+          ./scripts/feeds install -a
+          cd -
+      - name: Build Packages
+        run: |
+          cd "$SDK_HOME"
+          make defconfig
+          make package/${PACKAGE_NAME}/{clean,compile} V=s
+          find "$SDK_HOME/bin/" -type f -name "*.ipk" -exec ls -lh {} \;
+          cd -
+      - name: Copy Bin Files
+        run: |
+          find "$SDK_HOME/bin/" -type f -name "${PACKAGE_NAME}*.ipk" -exec cp {} "${{ github.workspace }}" \;
+          find "${{ github.workspace }}" -type f -name "*.ipk" -exec ls -lh {} \;
 
-      - name: Store packages
-        uses: actions/upload-artifact@main
+      - name: Release and Upload Assets
+        uses: softprops/action-gh-release@v1
         with:
-          name: ${{ matrix.arch }}-packages
-          path: bin/packages/${{ matrix.arch }}/action/*.ipk
+          files: "*.ipk"
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  
+      # - name: Store packages
+      #   uses: actions/upload-artifact@main
+      #   with:
+      #     name: ${{ matrix.arch }}-packages
+      #     path: bin/packages/${{ matrix.arch }}/action/*.ipk
